services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/static:ro
      - ./bibles:/app/bibles:ro
    environment:
      PORT: "3000"
